name: Build

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  build:
    name: Build on ${{ matrix.arch }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [amd64, arm64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install CMake & dependencies
        run: sudo apt-get update && sudo apt-get install -y cmake build-essential g++ gcc-aarch64-linux-gnu g++-aarch64-linux-gnu

      - name: Configure and Build
        run: |
          mkdir build
          cd build
          if [[ "${{ matrix.arch }}" == "arm64" ]]; then
            cmake .. -DCMAKE_SYSTEM_NAME=Linux -DCMAKE_SYSTEM_PROCESSOR=aarch64 \
              -DCMAKE_C_COMPILER=aarch64-linux-gnu-gcc \
              -DCMAKE_CXX_COMPILER=aarch64-linux-gnu-g++
          else
            cmake ..
          fi
          make

      - name: Save binary artifact
        uses: actions/upload-artifact@v4
        with:
          name: server-${{ matrix.arch }}
          path: build/server

  release:
    name: Publish binaries
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download all build artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            artifacts/server-amd64/my_app
            artifacts/server-arm64/my_app
